id: IFA0C074A
legacy_id: P006765
ocr_import_info:
  bdrc_scan_id: W1KG5705
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T17:38:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:20:53.509735+00:00'
last_modified: 2022-09-01 01:22:56.267035
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5705
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5705
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྣམ་གྲོལ་འདོད་འཇོ་རིས་མེད་དཔེ་རྙིང་ཁང་གི་ཚད་ལྡན་ངེས་དོན་དཔེ་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.7821745944077315
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG5708:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5708
      total_pages: 684
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5708.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.747644550585594
    legacy_id: v002
  I1KG5707:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5707
      total_pages: 662
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5707.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8107712666030059
    legacy_id: v001
  I1KG5710:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5710
      total_pages: 708
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG5710.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7720941947635768
    legacy_id: v004
  I1KG5712:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5712
      total_pages: 666
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG5712.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8480761546452774
    legacy_id: v006
  I1KG5709:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5709
      total_pages: 688
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG5709.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7516052597560218
    legacy_id: v003
  I1KG5711:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5711
      total_pages: 474
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG5711.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7734415899198809
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
