id: IFA0C074A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:43:53+00:00'
last_modified: '2022-06-08T06:42:15.641964+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5705
  title: རྣམ་གྲོལ་འདོད་འཇོ་རིས་མེད་དཔེ་རྙིང་ཁང་གི་ཚད་ལྡན་ངེས་དོན་དཔེ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F311:
      image_group_id: I1KG5707
      title: ''
      total_pages: 662
      order: 1
      base_file: F311.txt
    4B9E:
      image_group_id: I1KG5708
      title: ''
      total_pages: 684
      order: 2
      base_file: 4B9E.txt
    49D4:
      image_group_id: I1KG5709
      title: ''
      total_pages: 688
      order: 3
      base_file: 49D4.txt
    4A38:
      image_group_id: I1KG5710
      title: ''
      total_pages: 708
      order: 4
      base_file: 4A38.txt
    7F58:
      image_group_id: I1KG5711
      title: ''
      total_pages: 474
      order: 5
      base_file: 7F58.txt
    '6860':
      image_group_id: I1KG5712
      title: ''
      total_pages: 666
      order: 6
      base_file: 6860.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
